version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    environment:
      - DATABASE_URL=mysql+pymysql://root:ororZZKkPTnvAPsrdXHDKuUjEsfSSOiQ@junction.proxy.rlwy.net:28681/railway
    ports:
      - "8000:8000"
